"""Second opinion on the جدول ۱ transcription.

``rules/patterns.yaml`` is generated by ``tools/extract_table1.py``, which reads
the PDF's cell grid with pdfplumber. That is one extraction method, and a
systematic error in it — a mis-mapped column band, a shifted row — would produce
a matrix that is confidently and uniformly wrong.

``table1_ocr_crosscheck.json`` is the same table read by an unrelated OCR pass,
covering **every row, 1-102**. Comparing the two catches exactly the class of
error that anchors against §8 cannot: anchors verify a handful of cells we
happened to read in prose, whereas this verifies the whole matrix.

The fixture is committed rather than regenerated from ``Docs/`` so the check runs
on every clone. A test that needs a 5 MB PDF present is a test that quietly
skips.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from moadian.rules import load_rules
from moadian.rules.violations import Obligation

CROSSCHECK = Path(__file__).parent / "table1_ocr_crosscheck.json"


@pytest.fixture(scope="module")
def crosscheck() -> dict:
    if not CROSSCHECK.is_file():
        raise FileNotFoundError(
            f"{CROSSCHECK} is missing; it is the independent check on the generated "
            "obligation matrix and must not be deleted"
        )
    return json.loads(CROSSCHECK.read_text(encoding="utf-8"))


def obligation_of(pattern_spec, wire: str, invoice_type: int) -> str:
    """What patterns.yaml says, in the vocabulary the fixture uses."""
    for section in pattern_spec.SECTIONS:
        rule = pattern_spec.section(section).get(wire)
        if rule is not None:
            return str(rule.for_type(invoice_type))
    return str(Obligation.NOT_APPLICABLE)


def test_the_fixture_covers_the_whole_table(crosscheck: dict) -> None:
    """All 102 rows of جدول ۱, not a sample."""
    assert len(crosscheck["rows"]) == 102
    assert len(crosscheck["_columns"]) == 16
    codes = sorted(entry["code"] for entry in crosscheck["rows"].values())
    assert codes == list(range(1, 103))


def test_every_transcribed_cell_agrees_with_the_independent_ocr(crosscheck: dict) -> None:
    """1,632 cells, two unrelated extraction methods. Any disagreement is a defect.

    If this fails, do not "fix" it by editing the fixture — open the PDF at p.14
    and settle which reading is right, because at that point neither source is
    trustworthy for the cell in question.
    """
    rules = load_rules()
    disagreements: list[str] = []
    compared = 0

    for wire, entry in crosscheck["rows"].items():
        for column, expected in entry["obligations"].items():
            invoice_type, pattern = (int(part) for part in column.split("/"))
            spec = rules.pattern(pattern)
            if spec is None:
                continue
            actual = obligation_of(spec, wire, invoice_type)
            compared += 1
            if actual != expected:
                disagreements.append(
                    f"{wire} (row {entry['code']}, نوع {invoice_type} الگوی {pattern}): "
                    f"patterns.yaml={actual} ocr={expected}"
                )

    assert compared >= 1600, f"only {compared} cells compared; the fixture may be truncated"
    assert not disagreements, "\n".join(disagreements)


@pytest.mark.parametrize(
    "wire,invoice_type,pattern,expected",
    [
        # Spot checks worth naming, because each one caught a real bug earlier.
        ("taxid", 1, 1, "required"),
        ("tob", 1, 1, "required"),
        ("tob", 2, 1, "optional"),  # the two invoice-type bands genuinely differ
        ("sstt", 1, 1, "optional"),  # was guessed required before the transcription
        ("dis", 1, 1, "required"),  # was guessed optional
        ("cdcn", 1, 1, "not_applicable"),  # customs field; not part of a plain sale
        # ...but only اختیاری where it does apply. Asserting "required" here was a
        # guess, and both sources refused it — which is the point of this file.
        ("cdcn", 1, 7, "optional"),
        ("setm", 2, 1, "not_applicable"),  # §8-22 rule 2 makes it implicit
    ],
)
def test_named_cells_match_the_ocr(
    crosscheck: dict, wire: str, invoice_type: int, pattern: int, expected: str
) -> None:
    ocr = crosscheck["rows"].get(wire)
    if ocr is not None and f"{invoice_type}/{pattern}" in ocr["obligations"]:
        assert ocr["obligations"][f"{invoice_type}/{pattern}"] == expected
    spec = load_rules().pattern(pattern)
    assert obligation_of(spec, wire, invoice_type) == expected
